FROM opensuse/tumbleweed:latest

# Install ssh server and configure it to allow passwordless root access
RUN zypper --non-interactive install openssh
RUN mkdir /var/run/sshd
COPY controller_key.pub /root/.ssh/authorized_keys
RUN ssh-keygen -A

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]



